#!/bin/bash
set -e

mkdir -p docs
rm -rf docs/*

node_modules/.bin/docco -t resources/docco.jst interactive.coffee.md
node_modules/.bin/coffee -co docs/javascripts interactive.coffee.md

cp -r resources/docco.css resources/public docs
cp resources/*.js docs/javascripts
cp docs/interactive.coffee.html docs/index.html
